#!/bin/sh

### Set perms ###
chown -hR root: /
chown -R user: /home/user

chmod 0755 -R /
chmod 0644 /etc/*
chmod -R 600 /root
chmod 0700 /root /init


### Mount points ###
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys


### Share ###
mkdir -p /mnt/
mount -t 9p -o trans=virtio mountpoint /mnt/ -oversion=9p2000.L,posixacl,sync
chmod 777 /mnt/
chown -R root: /mnt/


### Shell ###
cat /etc/motd
export ENV=/etc/profile

# Start the shell for the user (1000) or root (0)
setsid cttyhack setuidgid 0 sh

# Stop the VM once exited from the shell
poweroff -f
