# Global settings
export BUILD_JOBS=6
export CROSS_COMPILE=i686-linux-gnu-

# Busybox settings
export BUSYBOX_ARCH=x86
export BUSYBOX_VERSION=1.31.0

# Linux kernel settings
LINUX_ARCH=x86
LINUX_VERSION=4.16.18
LINUX_IMG=bzImage
